
services:
- docker

script:
- make all

before_deploy:
- make deploy

deploy:
  provider: pages
  local-dir: ./docs/
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  verbose: true
  on:
    branch: master
